# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dummy1_cpp <- function(args) {
    .Call(`_bobfunctions2_dummy1_cpp`, args)
}

sim_wrightfisher_cpp <- function(args, args_functions, args_progress) {
    .Call(`_bobfunctions2_sim_wrightfisher_cpp`, args, args_functions, args_progress)
}

box_blur_cpp <- function(m, d) {
    .Call(`_bobfunctions2_box_blur_cpp`, m, d)
}

